add label detection
IDEA-CCNL/GTS-Engine pull request #75
Opened 2023-01-12 07:29 UTC by jidu12

增添标签检测功能，自测已通过

![image](https://user-images.githubusercontent.com/81082317/212003556-4f8382a6-d32c-4f64-8cbe-c97f1b0651ec.png)
输出的result.json:
![image](https://user-images.githubusercontent.com/81082317/212004563-e991198a-a8fa-4f97-afb0-39d9f3c35092.png)

代码规范（flake8检验工具）
![image](https://user-images.githubusercontent.com/81082317/212003655-f1ef8afe-58ca-44f0-8c96-12e6b627b1d7.png)

2023-01-18 06:31 UTC, pskun requested changes

2023-01-18 06:31 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +sys.path.append('../')
不要写..，最好是os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

2023-01-18 06:31 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +    with open(os.path.join(data_path, 'tnews_test.json'), 'r',
为啥要写死？有其他数据怎么办？

2023-01-18 06:31 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +    with open(os.path.join(data_path, 'tnews_label.json'),
这里也是

2023-01-18 06:31 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +    total_vail_data = sample_input_data
vail是什么意思？

2023-01-18 06:31 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +    random.shuffle(negative_label_index)
为什么不用random.sample

2023-01-18 06:31 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +    start = time.time()
这个变量有什么作用？

2023-01-18 06:31 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +    input_data, input_labels, labels_info = read_data(data_path=data_path, result_path=result_path)
为什么要读一个result_path，不是应该写吗？

2023-01-18 06:31 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +        sentences, vail_data = take_sample(sample_input_data=sample_input_data, current_label=current_label)
这个函数，可以用sklearn的StratifiedShuffleSplit替换吗？

2023-01-18 06:31 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +        while n < 2:
为什么不把while里面的逻辑拆成函数？

2023-01-18 06:31 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +            start1 = time.time()
这个变量有什么作用？

2023-01-18 06:31 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +            logger.info("every_time:{}".format(time.time() - start1))
这个logger不需要

2023-01-18 06:31 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +                labels_info[current_label] = ["2", current_label_id, label_f1]
这里labels_info应该是之前需要多次修改和检测的逻辑吧，这里还需要吗？

2023-01-18 06:31 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +    os.environ["CUDA_VISIBLE_DEVICES"] = "5"
环境变量由用户指定，不要写死，而且写在这里不会起作用的

2023-01-18 06:31 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +    total_parser = argparse.ArgumentParser()
先写argparse再下载模型

2023-01-18 06:31 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +    total_parser.add_argument(
不需要指定model_path，因为默认都用Erlangshen-UniMC-MegatronBERT-1.3B-Chinese，这是用户不能改的

2023-01-18 06:31 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +        default=os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "examples/text_classification"),
为啥要写死用户需要输入的数据？

2023-01-18 07:09 UTC, jidu12 commented on gts_engine/label_detection/label_detection.py
> +            start1 = time.time()
已删除

2023-01-18 07:09 UTC, jidu12 commented on gts_engine/label_detection/label_detection.py
> +    start = time.time()
已删除

2023-01-18 09:58 UTC, jidu12 commented on gts_engine/label_detection/label_detection.py
> +    random.shuffle(negative_label_index)
一博这里取样数量是有可能大于列表的长度的
经测试random.sample在取样数大于列表长度的情况下会报错

2023-01-18 09:58 UTC, jidu12 commented on gts_engine/label_detection/label_detection.py
> +                labels_info[current_label] = ["2", current_label_id, label_f1]
经测试，有一个在对原始result读取的逻辑可以删除（已完成），其他的逻辑会影响到检测过程，删除了就没法得到正确结果了

2023-01-18 09:58 UTC, jidu12 commented on gts_engine/label_detection/label_detection.py
> +    total_vail_data = sample_input_data
一博说这里是想表示有效数据的意思，应该是拼错了，我修改为了“val”

2023-01-18 09:58 UTC, jidu12 commented on gts_engine/label_detection/label_detection.py
> +        sentences, vail_data = take_sample(sample_input_data=sample_input_data, current_label=current_label)
不太熟悉这个函数，但是我理解这个函数应该没法做到正负采样的逻辑

2023-01-18 10:01 UTC, jidu12 commented on gts_engine/label_detection/label_detection.py
> +    with open(os.path.join(data_path, 'tnews_label.json'),
已修改

2023-01-28 04:08 UTC, pskun requested changes

2023-01-28 04:08 UTC, pskun commented on README.md
> +python label_detection.py --label_path /cognitive_comp/zhubohan/GTS-Engine/examples/text_classification/tnews_label.json --data_path /cognitive_comp/zhubohan/GTS-Engine/examples/text_classification/t
改成相对路径

2023-01-28 04:08 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +    # sample_count_every_class = int(6000/labels_count)   # 600/(0.05 * 2)
删掉没用的注释

2023-01-28 04:08 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +    random.shuffle(negative_label_index)
> 一博这里取样数量是有可能大于列表的长度的 经测试random.sample在取样数大于列表长度的情况下会报错

random.sample(data, min(len(data), n))

2023-01-28 04:08 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +        while n < 2:
下一次提交代码时考虑拆分成函数

2023-01-28 04:08 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +        default=os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "examples/text_classification/tnews_label.json"),
最好不要设置default

2023-01-28 04:08 UTC, pskun commented on gts_engine/label_detection/label_detection.py
> +        default=os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "examples/text_classification/tnews_test.json"),
这里也是

2023-01-28 07:44 UTC, jidu12 commented on README.md
> +python label_detection.py --label_path /cognitive_comp/zhubohan/GTS-Engine/examples/text_classification/tnews_label.json --data_path /cognitive_comp/zhubohan/GTS-Engine/examples/text_classification/t
> 改成相对路径

已修改 
注： 这里 刚刚测试的时候前面的.py文件如果不写全绝对路径的话前面导包（第九行）的时候会出问题，sys.path会挂一个空的路径，然后找不到父级目录的组件。。年前的时候没遇到这个问题 很奇怪

2023-01-28 07:45 UTC, jidu12 commented on gts_engine/label_detection/label_detection.py
> +    # sample_count_every_class = int(6000/labels_count)   # 600/(0.05 * 2)
> 删掉没用的注释

已修改

2023-01-28 07:45 UTC, jidu12 commented on gts_engine/label_detection/label_detection.py
> +    random.shuffle(negative_label_index)
👌

2023-01-28 07:46 UTC, jidu12 commented on gts_engine/label_detection/label_detection.py
> +        while n < 2:
这里while拆过一个 total_predicts = predict_process(two_choices=two_choices,
                                             tokenizer=tokenizer,
                                             sentences=sentences,
                                             model=model)
函数，其他的部分耦合度太高，拆的话要传的参数太多了

2023-01-28 07:52 UTC, jidu12 commented on README.md
> +python label_detection.py --label_path /cognitive_comp/zhubohan/GTS-Engine/examples/text_classification/tnews_label.json --data_path /cognitive_comp/zhubohan/GTS-Engine/examples/text_classification/t
已修改

2023-01-28 08:09 UTC, jidu12 commented on gts_engine/label_detection/label_detection.py
> +        default=os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "examples/text_classification/tnews_label.json"),
好滴

2023-01-28 08:09 UTC, jidu12 commented on gts_engine/label_detection/label_detection.py
> +        default=os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "examples/text_classification/tnews_test.json"),
好的

2023-01-30 02:07 UTC, pskun approved these changes

2023-01-30 02:07 UTC, merged