Dev fyc summary
IDEA-CCNL/GTS-Engine pull request #83
Opened 2023-02-20 08:45 UTC by savannahfan

八卦炉新增摘要生成任务，修改README.md文档（任务类型、更新日志），代码已经经过规范检查。

2023-02-20 09:00 UTC, QianguoS commented on README.md
>  - `2022/12/30`：正式发布八卦炉引擎Beta版本，支持以110M参数的base模型为底座的分类、信息抽取类型任务；
更新日志中的历史更新可以不用删除

2023-02-20 09:00 UTC, QianguoS commented on README.md
>  - `2022/11/22`：乾坤鼎分类任务增加高级模式：支持用户上传无标注数据进行Self Training，进一步提升效果；
同上

2023-02-20 09:00 UTC, QianguoS commented on README.md
>  - `2022/11/18`：正式发布乾坤鼎引擎Beta版本，FewCLUE榜单任务训练细节将陆续公开；
同上

2023-02-20 09:01 UTC, QianguoS commented on examples/summary/run_inference_bagualu_lcsts.sh
> +export CUDA_VISIBLE_DEVICES=5
CUDA_VISIBLE_DEVICES默认设置为0，降低用户一键启动的出错的概率

2023-02-20 09:04 UTC, QianguoS commented on examples/summary/run_inference_bagualu_lcsts.slurm
> +    --output_path=$TASK_DIR/output.json \
slum脚本可以不用提交

2023-02-20 09:04 UTC, QianguoS commented on examples/summary/run_train_bagualu_lcsts.sh
> +export CUDA_VISIBLE_DEVICES=7
CUDA_VISIBLE_DEVICES默认设置为0

2023-02-20 09:05 UTC, QianguoS commented on examples/summary/run_train_bagualu_lcsts.slurm
> +    --seed=123
slum脚本可以不用提交

2023-02-20 09:35 UTC, QianguoS commented on gts_engine/bagualu/entrances/summary/training_pipeline_std.py
> +        new_preds = [chinese_char_tokenize(d['pred']) for d in res_data]
局部变量换下，见名知义，比如tokenize_preds

2023-02-20 09:35 UTC, QianguoS commented on gts_engine/bagualu/entrances/summary/training_pipeline_std.py
> +        new_labels = [chinese_char_tokenize(d['summary']) for d in res_data]
同上

2023-02-20 09:36 UTC, QianguoS commented on gts_engine/bagualu/models/summary/eval_utils.py
> +        new_preds = [chinese_char_tokenize(p) for p in preds]
同上

2023-02-20 09:36 UTC, QianguoS commented on gts_engine/bagualu/models/summary/eval_utils.py
> +        new_labels = [chinese_char_tokenize(label) for label in labels]
同上

2023-02-21 02:43 UTC, QianguoS approved these changes

2023-02-21 02:43 UTC, merged

2023-02-21 02:57 UTC, pskun requested changes

2023-02-21 02:57 UTC, pskun commented on examples/summary/run_inference_bagualu_lcsts.sh
> +#!/bin/bash
文件名应该统一成run_inference_bagualu.sh？

2023-02-21 02:57 UTC, pskun commented on gts_engine/bagualu/arguments/summary/arguments_std.py
> +    """信息抽取finetune参数."""
是信息抽取吗？

2023-02-21 02:57 UTC, pskun commented on gts_engine/bagualu/arguments/summary/arguments_std.py
> +    """信息抽取finetune参数."""
同

2023-02-21 02:57 UTC, pskun commented on gts_engine/bagualu/dataloaders/summary/data_module.py
> +        if labels is None:
```python
batch_data = {
                'id': batch_data['id'],
                'text': batch_data['text'],
                'input_ids': input_ids,
                'attention_mask': attention_mask,
            }
if labels is not None:
    batch_data["summary"] = summary
    batch_data["labels"] = labels
```

2023-02-21 02:57 UTC, pskun commented on gts_engine/bagualu/models/summary/eval_utils.py
> +class SummerizationEvaluation(nn.Module):
SummarizationEvaluation

2023-02-21 02:57 UTC, pskun commented on gts_engine/bagualu/models/summary/eval_utils.py
> +            line_in_chars += " "
line_in_chars = []，line_in_chars.append, " ".join(line_in_chars)
在运行效率上要比+=好

2023-02-21 02:57 UTC, pskun commented on gts_engine/bagualu/models/summary/eval_utils.py
> +def get_summerization_report(y_true: List[str], y_pred: List[str],
summarization

2023-02-21 02:57 UTC, pskun commented on gts_engine/bagualu/models/summary/lit_model.py
> +    """BagualuIELitModel.
BagualuSummaryLitModel

2023-02-21 02:57 UTC, pskun commented on gts_engine/bagualu/models/summary/lit_model.py
> +                self._logger.info("num_data: %d", self.num_data)
应该统一代码成f"xx"的形式